<?xml version="1.0" encoding="UTF-8" standalone="yes"?>
<ns2:test-suite start="1481583666064" stop="1481584011028" xmlns:ns2="urn:model.allure.qatools.yandex.ru">
    <name>Default suite : Default test</name>
    <title>Default suite : Default test</title>
    <test-cases>
        <test-case start="1481583685700" stop="1481583700246" status="passed">
            <name>testAddPdocutWithEmptyDeliveryAndCategory</name>
            <steps/>
            <attachments/>
            <labels>
                <label name="host" value="DESKTOP-HEOVU1M"/>
                <label name="thread" value="7412@DESKTOP-HEOVU1M.main(1)"/>
            </labels>
        </test-case>
        <test-case start="1481583714230" stop="1481583733019" status="passed">
            <name>testAddProductCickOnYesInConfirmationPopup</name>
            <steps/>
            <attachments/>
            <labels>
                <label name="host" value="DESKTOP-HEOVU1M"/>
                <label name="thread" value="7412@DESKTOP-HEOVU1M.main(1)"/>
            </labels>
        </test-case>
        <test-case start="1481583747569" stop="1481583770090" status="passed">
            <name>testAddProductCickOnYesInConfirmationPopupAfterErrors</name>
            <steps/>
            <attachments/>
            <labels>
                <label name="host" value="DESKTOP-HEOVU1M"/>
                <label name="thread" value="7412@DESKTOP-HEOVU1M.main(1)"/>
            </labels>
        </test-case>
        <test-case start="1481583784057" stop="1481583799414" status="passed">
            <name>testAddProductConfirmationPopup</name>
            <steps/>
            <attachments/>
            <labels>
                <label name="host" value="DESKTOP-HEOVU1M"/>
                <label name="thread" value="7412@DESKTOP-HEOVU1M.main(1)"/>
            </labels>
        </test-case>
        <test-case start="1481583813887" stop="1481583829731" status="passed">
            <name>testAddProductWithEmptyAllFields</name>
            <steps/>
            <attachments/>
            <labels>
                <label name="host" value="DESKTOP-HEOVU1M"/>
                <label name="thread" value="7412@DESKTOP-HEOVU1M.main(1)"/>
            </labels>
        </test-case>
        <test-case start="1481583844251" stop="1481583859999" status="passed">
            <name>testAddProductWithEmptyCategory</name>
            <steps/>
            <attachments/>
            <labels>
                <label name="host" value="DESKTOP-HEOVU1M"/>
                <label name="thread" value="7412@DESKTOP-HEOVU1M.main(1)"/>
            </labels>
        </test-case>
        <test-case start="1481583874362" stop="1481583890751" status="passed">
            <name>testAddProductWithEmptyMandatoryFields</name>
            <steps/>
            <attachments/>
            <labels>
                <label name="host" value="DESKTOP-HEOVU1M"/>
                <label name="thread" value="7412@DESKTOP-HEOVU1M.main(1)"/>
            </labels>
        </test-case>
        <test-case start="1481583904899" stop="1481583922864" status="broken">
            <name>testAddProductWithFilledAllFields</name>
            <failure>
                <message>NullPointerException: null</message>
                <stack-trace>java.lang.NullPointerException
	at roi4cio.TestAddProduct.testAddProductWithFilledAllFields(TestAddProduct.java:147)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:86)
	at org.testng.internal.Invoker.invokeMethod(Invoker.java:643)
	at org.testng.internal.Invoker.invokeTestMethod(Invoker.java:820)
	at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:1128)
	at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:129)
	at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:112)
	at org.testng.TestRunner.privateRun(TestRunner.java:782)
	at org.testng.TestRunner.run(TestRunner.java:632)
	at org.testng.SuiteRunner.runTest(SuiteRunner.java:366)
	at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:361)
	at org.testng.SuiteRunner.privateRun(SuiteRunner.java:319)
	at org.testng.SuiteRunner.run(SuiteRunner.java:268)
	at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
	at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:86)
	at org.testng.TestNG.runSuitesSequentially(TestNG.java:1244)
	at org.testng.TestNG.runSuitesLocally(TestNG.java:1169)
	at org.testng.TestNG.run(TestNG.java:1064)
	at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:132)
	at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:236)
	at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:81)
</stack-trace>
            </failure>
            <steps/>
            <attachments/>
            <labels>
                <label name="host" value="DESKTOP-HEOVU1M"/>
                <label name="thread" value="7412@DESKTOP-HEOVU1M.main(1)"/>
            </labels>
        </test-case>
        <test-case start="1481583937499" stop="1481583951886" status="passed">
            <name>testAddProductWithoutCountry</name>
            <steps/>
            <attachments/>
            <labels>
                <label name="host" value="DESKTOP-HEOVU1M"/>
                <label name="thread" value="7412@DESKTOP-HEOVU1M.main(1)"/>
            </labels>
        </test-case>
        <test-case start="1481583966064" stop="1481583979900" status="broken">
            <name>testAddProduct</name>
            <failure>
                <message>NullPointerException: null</message>
                <stack-trace>java.lang.NullPointerException
	at roi4cio.TestAddProduct.testAddProduct(TestAddProduct.java:36)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:86)
	at org.testng.internal.Invoker.invokeMethod(Invoker.java:643)
	at org.testng.internal.Invoker.invokeTestMethod(Invoker.java:820)
	at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:1128)
	at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:129)
	at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:112)
	at org.testng.TestRunner.privateRun(TestRunner.java:782)
	at org.testng.TestRunner.run(TestRunner.java:632)
	at org.testng.SuiteRunner.runTest(SuiteRunner.java:366)
	at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:361)
	at org.testng.SuiteRunner.privateRun(SuiteRunner.java:319)
	at org.testng.SuiteRunner.run(SuiteRunner.java:268)
	at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
	at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:86)
	at org.testng.TestNG.runSuitesSequentially(TestNG.java:1244)
	at org.testng.TestNG.runSuitesLocally(TestNG.java:1169)
	at org.testng.TestNG.run(TestNG.java:1064)
	at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:132)
	at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:236)
	at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:81)
</stack-trace>
            </failure>
            <steps/>
            <attachments/>
            <labels>
                <label name="host" value="DESKTOP-HEOVU1M"/>
                <label name="thread" value="7412@DESKTOP-HEOVU1M.main(1)"/>
            </labels>
        </test-case>
        <test-case start="1481583994392" stop="1481584010739" status="failed">
            <name>testAddProductWithSameName</name>
            <failure>
                <message>AssertionError: Product with the same title couldn't be created expected [Некоторые ошибки
Продукт с таким именем уже существует] but found [Некоторые ошибки
Категория продукта: Задано пустое значение.]</message>
                <stack-trace>java.lang.AssertionError: Product with the same title couldn't be created expected [Некоторые ошибки
Продукт с таким именем уже существует] but found [Некоторые ошибки
Категория продукта: Задано пустое значение.]
	at org.testng.Assert.fail(Assert.java:94)
	at org.testng.Assert.failNotEquals(Assert.java:513)
	at org.testng.Assert.assertEqualsImpl(Assert.java:135)
	at org.testng.Assert.assertEquals(Assert.java:116)
	at org.testng.Assert.assertEquals(Assert.java:190)
	at roi4cio.TestAddProduct.testAddProductWithSameName(TestAddProduct.java:44)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:86)
	at org.testng.internal.Invoker.invokeMethod(Invoker.java:643)
	at org.testng.internal.Invoker.invokeTestMethod(Invoker.java:820)
	at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:1128)
	at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:129)
	at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:112)
	at org.testng.TestRunner.privateRun(TestRunner.java:782)
	at org.testng.TestRunner.run(TestRunner.java:632)
	at org.testng.SuiteRunner.runTest(SuiteRunner.java:366)
	at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:361)
	at org.testng.SuiteRunner.privateRun(SuiteRunner.java:319)
	at org.testng.SuiteRunner.run(SuiteRunner.java:268)
	at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
	at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:86)
	at org.testng.TestNG.runSuitesSequentially(TestNG.java:1244)
	at org.testng.TestNG.runSuitesLocally(TestNG.java:1169)
	at org.testng.TestNG.run(TestNG.java:1064)
	at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:132)
	at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:236)
	at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:81)
</stack-trace>
            </failure>
            <steps/>
            <attachments/>
            <labels>
                <label name="host" value="DESKTOP-HEOVU1M"/>
                <label name="thread" value="7412@DESKTOP-HEOVU1M.main(1)"/>
            </labels>
        </test-case>
    </test-cases>
    <labels>
        <label name="framework" value="TestNG"/>
        <label name="language" value="JAVA"/>
    </labels>
</ns2:test-suite>
